# Generated by Django 3.2.12 on 2022-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', max_length=64),
        ),
    ]
