# Generated by Django 3.2.12 on 2022-02-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='shrsrc_id',
            field=models.IntegerField(default=-1),
        ),
    ]
