# Generated by Django 3.2.12 on 2022-02-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0010_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster_id',
        ),
    ]
