# Generated by Django 3.2.12 on 2022-02-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0011_remove_post_poster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shrsrc_id',
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.user')),
            ],
        ),
    ]
