# Generated by Django 3.2.12 on 2022-02-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0012_auto_20220222_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='src',
            field=models.IntegerField(default=-1),
        ),
    ]
