# Generated by Django 3.2.12 on 2022-02-23 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0013_share_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField(default=0)),
                ('user2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friendmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.CharField(max_length=256)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.user')),
            ],
        ),
    ]
