# Generated by Django 3.2.12 on 2022-02-24 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0014_friendmsg_friendship_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user2', models.IntegerField(default=0)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.RemoveField(
            model_name='friendmsg',
            name='post',
        ),
        migrations.RemoveField(
            model_name='friendmsg',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_num',
        ),
        migrations.AddField(
            model_name='post',
            name='op',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 17, 22, 53, 339922, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='src',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='Share',
        ),
        migrations.AddField(
            model_name='friendmsg',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userpage.friendlink'),
            preserve_default=False,
        ),
    ]
