# Generated by Django 3.2.12 on 2022-02-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0015_auto_20220224_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='op',
            field=models.CharField(max_length=50),
        ),
    ]
