# Generated by Django 3.2.12 on 2022-02-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0016_alter_post_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='src',
            field=models.IntegerField(),
        ),
    ]
