# Generated by Django 3.2.12 on 2022-03-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0017_alter_post_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userpage.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userpage.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='src',
            field=models.IntegerField(default=-1),
        ),
    ]
