# Generated by Django 3.2.12 on 2022-03-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0021_auto_20220301_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_num',
        ),
    ]
