# Generated by Django 3.2.12 on 2022-03-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0022_auto_20220301_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlink',
            name='accepted',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='Friendmsg',
        ),
    ]
