# Generated by Django 3.2.12 on 2022-03-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0023_auto_20220301_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlink',
            old_name='user1',
            new_name='user_get',
        ),
        migrations.RemoveField(
            model_name='friendlink',
            name='user2',
        ),
        migrations.AddField(
            model_name='friendlink',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_send', to='userpage.user'),
            preserve_default=False,
        ),
    ]
