# Generated by Django 3.2.12 on 2022-03-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0024_auto_20220301_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlink',
            name='user_get',
        ),
        migrations.AddField(
            model_name='friendlink',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_get', to='userpage.user'),
            preserve_default=False,
        ),
    ]
